controller:
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - kubernetes-credentials-provider
    - github
  serviceType: LoadBalancer
persistence:
  size: 20Gi
  storageClass: "gp3"