apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: status-checker-ingress
  annotations:
    # AWS Load Balancer Controller에게 ALB 생성 명령
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    # 타겟 타입을 'ip'로 설정 (Fargate나 최근 EKS 표준)
    alb.ingress.kubernetes.io/target-type: ip
    # ACM 인증서 ARN
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:ap-northeast-2:808985145578:certificate/a6fa7b8f-a325-4b93-8da4-1eae29a01523
    # HTTP 접속을 HTTPS로 자동 리다이렉트
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": { "Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
spec:
  ingressClassName: alb 
  rules:
    - host: "fastcampus-jihyun.link" # 도메인
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: status-checker-service # 서비스 이름
                port:
                  number: 80

