apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: LoadBalancer # AWS ALB와 연동되어 외부 주소 생성
  selector:
    app: python-app
  ports:
  - protocol: TCP
    port: 80          # 외부에서 접속할 포트
    targetPort: 8000  # 컨테이너 내부 포트와 연결